# Generated by Django 6.0.1 on 2026-01-27 13:29

import utils.id_generators.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortURL',
            fields=[
                ('id', models.BigIntegerField(default=utils.id_generators.manager.IDManager.generate_id, editable=False, primary_key=True, serialize=False)),
                ('long_url', models.URLField(max_length=2048)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('short_code', models.CharField(max_length=15, unique=True)),
                ('click_count', models.IntegerField(default=0)),
            ],
            options={
                'indexes': [models.Index(fields=['short_code'], name='api_service_short_c_025bea_idx')],
            },
        ),
    ]
